mock_code:
  wannier90: /home/dmarchand/Install/qe-6.6/bin/wannier90.x 
  pw: /home/dmarchand/Install/qe-6.6/bin/pw.x
  pw2wannier90: /home/dmarchand/Install/qe-6.6/bin/pw2wannier90.x
  vasp: /bin/true
