language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
env:
  - TEST_TYPE="tests" INSTALL_TYPE="testing"
  - TEST_TYPE="tests" INSTALL_TYPE="testing_sdist"
jobs:
  include:
  - python: "3.7"
    env: TEST_TYPE="pre-commit" INSTALL_TYPE="dev_precommit"
cache: pip
sudo: true
services:
  - postgresql
  - rabbitmq
addons:
  apt:
    packages:
      - rabbitmq-server
      - python3
      - python3-tk
      - python3-pip
      - python3-numpy
      - python3-h5py
      - python3-matplotlib
      - libhdf5-dev
      - gfortran
      - libblas-dev
      - liblapack-dev
before_install:
  - sudo pip3 install -U pip setuptools
  - sudo pip3 install bands-inspect
  - sudo pip3 install tbmodels
  - sudo service postgresql restart
install:
  - ./.travis-data/install_script.sh
script:
  - travis_wait 60 ./.travis-data/test_script.sh
